version: '3.8'
services:
  tg2sip:
    build: .
    image: tg2sip-go
    volumes:
      - ./settings.ini:/app/settings.ini:ro
      - ./data:/data
    ports:
      - "5060:5060/udp"
    restart: unless-stopped
    stdin_open: true    # keep STDIN open for interactive login
    tty: true           # allocate a pseudo-TTY for login prompts
